name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-migrate:
    runs-on: ubuntu-latest

    # To swich for github secrets
    # env:
    #   DB_USER: postgres
    #   DB_PASSWORD: postgres
    #   DB_HOST: localhost
    #   DB_PORT: 5432
    #   DB_NAME: panierquebec

      
    # services:
    #   postgres:
    #     image: postgres:15
    #     ports:
    #       - 5432:5432
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: panierquebec
    #     options: >-
    #       --health-cmd "pg_isready -U postgres"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      # - name: Install golang-migrate CLI
      #   run: |
      #     go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      # - name: Run migrations
      #   run: |
      #     migrate -path migrations -database "postgres://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.DB_NAME }}?sslmode=disable" up


      - name: Setup sqlc
        uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.29.0'

      # - name: Sqlc diff
      #   run: sqlc diff

      - name: Sqlc generate
        run: sqlc generate

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          buf_api_token: ${{ secrets.BUF_REGISTRY_TOKEN }}
      
      - name: Run Buf lint
        run: buf lint

      - name: Install Tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest

      # - name: Run Buf breaking
      #   run: buf breaking --against-registry buf.build/panierquebec/panierquebec

      - name: Run Buf generate
        run: buf generate

      - name: Go mod tidy
        run: go mod tidy

      - name: Lint
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...

      - name: Build 
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o build/panierquebec_backend_linux_amd64 ./cmd/server/main.go

      - name: Build for Macos ARM
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -v -o build/panierquebec_backend_darwin_arm64 ./cmd/server/main.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: panierquebec_backend
          path: ./build
          