name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-test-migrate:
    runs-on: ubuntu-latest

    # To swich for github secrets
    # env:
    #   DB_USER: postgres
    #   DB_PASSWORD: postgres
    #   DB_HOST: localhost
    #   DB_PORT: 5432
    #   DB_NAME: panierquebec

      
    # services:
    #   postgres:
    #     image: postgres:15
    #     ports:
    #       - 5432:5432
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: panierquebec
    #     options: >-
    #       --health-cmd "pg_isready -U postgres"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      # - name: Install golang-migrate CLI
      #   run: |
      #     go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      # - name: Run migrations
      #   run: |
      #     migrate -path migrations -database "postgres://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.DB_NAME }}?sslmode=disable" up
      
      - name: Go mod tidy
        run: go mod tidy

      - uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.29.0'

      - name: Sqlc diff
        run: sqlc diff

      - name: Sqlc generate
        run: sqlc generate

      - name: Lint
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...

      - name: Build 
        run: go build -v -o build/panierquebec_backend_linux_amd64 ./cmd/panierquebec_backend
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./build